# G1 29dof实物部署配置
robot:
  num_joints: 29  # 29dof机器人关节数
  invadlid_joints_id: [13, 14] # 无效关节id waist roll 与 waist pitch
  
observations:
  num_single_obs: 76      # 单步观测维度 (基于23dof策略格式)
  history_length: 6       # 历史步数
  total_obs_dim: 456      # 总维度: 76 * 6
  
observation_scales:
  ang_vel: 0.25
  dof_pos: 1.0
  dof_vel: 0.05

control:
  control_type: 'P'
  action_scale: 0.25
  # 29dof关节顺序: 左腿(6) + 右腿(6) + 腰部(3) + 左臂(4) + 左手腕(3) + 右臂(4) + 右手腕(3) + 额外关节(2)
  # kp: [150, 150, 150, 200, 40, 40,     # 左腿
  #      150, 150, 150, 200, 40, 40,     # 右腿
  #      100, 100, 100,              # 腰部
  #      100, 100, 100, 100,             # 左臂
  #      40, 40, 40,                     # 左手腕 (降低增益减少晃动)
  #      100, 100, 100, 100,             # 右臂
  #      40, 40, 40 ]                    # 右手腕 (降低增益减少晃动)         

  # 1.
    # kp: [200, 200, 200, 275, 40, 40,     # 左腿
        # kp: [200, 200, 200, 300, 40, 40,     # 左腿
                # kp: [230, 230, 230, 320, 60, 60     # 左腿
                # 230, 230, 230, 300, 60, 60,  

                # 200, 200, 200, 270, 55, 55,

  kp: [200, 200, 200, 270, 55, 55,     # 左腿
       200, 200, 200, 270, 55, 55,     # 右腿
       100, 100, 100,                  # 腰部
       100, 100, 100, 100,             # 左臂
       50, 50, 50,                     # 左手腕 (降低增益减少晃动)
       100, 100, 100, 100,             # 右臂
       50, 50, 50 ]                    # 右手腕 (降低增益减少晃动)                   

  kd: [4, 4, 4, 6, 2, 2,              # 左腿
       4, 4, 4, 6, 2, 2,              # 右腿
       4, 4, 4,                        # 腰部
       4, 4, 4, 4,                    # 左臂
       6, 6, 6,                       # 左手腕 (增加阻尼减少振荡)
       4, 4, 4, 4,                    # 右臂
       6, 6, 6 ]                     # 右手腕 (增加阻尼减少振荡)

model:
  #default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_real/g1_29dof/models/policy_g1_platform_12000.onnx"

  #default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_real/g1_29dof/models/policy_g1_ground_12000_2.onnx"

  default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_real/g1_29dof/models/policy_g1_platform_12000_3.onnx"

initial_pose:
  joint_angles: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,  # 左腿
                 -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,  # 右腿
                 0.0,                               # 腰部
                 0.0, 0.3, 0.0, 1.57,               # 左臂
                 0.0, 0.0, 0.0,                    # 左手腕
                 0.0, -0.3, 0.0, 1.57,              # 右臂
                 0.0, 0.0, 0.0,                    # 右手腕
                 0.0, 0.0]   
reset:
  joint_idx: [19, 20, 21, 
              26, 27, 28]                      # 左右手腕
  joint_angel: [0.0, 0.0, 0.0, 
                0.0, 0.0, 0.0]

# 通信配置
communication:
  lowcmd_topic: "rt/lowcmd"
  lowstate_topic: "rt/lowstate"
  network_interface: "eno1"  # 网络接口
