# G1平台部署配置
simulation:
  xml_path: "/home/shenlan/HoST/legged_gym/resources/robots/g1/g1_23dof_platform.xml"
  simulation_dt: 0.002
  control_decimation: 10

robot:
  num_joints: 23
  
observations:
  num_single_obs: 76      # 单步观测维度
  history_length: 6       # 历史步数
  total_obs_dim: 456      # 总维度: 76 * 6
  
observation_scales:
  ang_vel: 0.25
  dof_pos: 1.0
  dof_vel: 0.05

control:
  control_type: 'P'
  action_scale: 0.3
  # 关节顺序: 左腿(6) + 右腿(6) + 腰部(1) + 左臂(5) + 右臂(5)
  kp: [200, 170, 170, 275, 40, 40,
       200, 170, 170, 275, 40, 40,
       140,
       100, 100, 100, 100, 100,
       100, 100, 100, 100, 100]

  kd: [4, 4, 4, 6, 2, 2,
       4, 4, 4, 6, 2, 2,
       4, 
       4, 4, 4, 4, 4,
       4, 4, 4, 4, 4]

model:
  #default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_mujoco/g1_platform/models/policy_g1_platform_4000.onnx"

  #default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_mujoco/g1_platform/models/policy_g1_platform_12000.onnx"

  #default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_mujoco/g1_platform/models/policy_g1_platform_12500.onnx"

  #default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_mujoco/g1_platform/models/policy_g1_platform_3500.onnx"

  default_model_path: "/home/shenlan/HoST/legged_gym/deploy/deploy_mujoco/g1_platform/models/policy_g1_platform_12000_3.onnx"

  

initial_pose:
  position: [-0.5, 0.0, 0.7]  # x, y, z坐标
  orientation: [0.0, 1.0, 0.0, 1.0]  # w, x, y, z四元数
  joint_angles: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,  # 左腿
                 -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,  # 右腿
                 0.0,                               # 腰部
                 0.0, 0.3, 0.0, 0.0, 0.0,          # 左臂
                 0.0, -0.3, 0.0, 0.0, 0.0]         # 右臂
